apiVersion: v1
kind: Pod

metadata:
  name: init-demo

spec:
  initContainers:
    - name: init
      image: busybox:latest
      command:
        - sh
        - -c
        - echo "Hello from Init Container" > /work/message.txt
      volumeMounts:
        - name: workdir
          mountPath: /work

  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: workdir
          mountPath: /work

  volumes:
    - name: workdir
      emptyDir: {}
