apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ZahaanMahajan/homelab.git
    targetRevision: v2.0.0
    path: kubernetes/applications/nextcloud
    helm: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
