apiVersion: v1
kind: Pod

metadata:
  name: cka-resource-error

spec:
  containers:
    - name: nginx
      image: nginx:latest

      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
