apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy

metadata:
  name: portfolio-proxy
  namespace: portfolio

spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                metallb.io/loadBalancerIPs: "192.168.29.241"
