replicaCount: 1

image:
  repository: ghcr.io/zahaanmahajan/portfolio
  tag: d4caeb0feb4cedf3eb1aae1630ed7b51d8934e44
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-creds

nodeSelector:
  workload: worker-node-01

tolerations:
  - key: workload
    operator: Equal
    value: worker-node-01
    effect: NoSchedule

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi

gateway:
  enabled: true
  name: portfolio-gateway
  className: envoy-gateway
  address: 192.168.29.241

route:
  enabled: true
  hostname: portfolio.zahaan.online

tls:
  enabled: true
  issuer: letsencrypt-production
  secretName: portfolio-zahaan-online-tls

envoyProxy:
  enabled: true
  name: portfolio-proxy
  loadBalancerIP: 192.168.29.241
