apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:lNh8/5Q=,iv:BMwgMD9QgEmd5/PVjHSqY3lZIGMJsh8whGFXnXjKGZQ=,tag:CnNX04PY64inPvqySPOlZQ==,type:str]
    admin-password: ENC[AES256_GCM,data:03SAYHO1JwbzsRSTrcs=,iv:27aC1J3aqHbBHmr3DIDOgEzNu+LZnuc9Jpf7wXygGo4=,tag:hGjyqK9mcvHIF/11dLz2vw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRmVhL3hHeHhnUHkvN0NQ
            RnVldTBTYm92ZEg3a000ODR4M01aNzlnQUNVCiswSkhVM0RhWGwrQ3Vac2Nkd3Aw
            SGVKMm1lZGZ5ZVNUajhEVXJjc3UxZ0kKLS0tIGVoRHZzVllodWJ0elhRU1BYajRE
            ZTFZT2NPUThDNE1ORzlMNWQxTzB3RmMK1jndwEu9/rGm0DbQoDsjG623JwMfGEQl
            G42M5sUHVwT0g6WO9aRzIHVlxixISDTdIP8hjecigb/EHdPEEUGBGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wu2jzk553srljakk8n6uwsfaqh7qdl40htxavzxtjn2yllzq4c0qqg2dtk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:56:58Z"
    mac: ENC[AES256_GCM,data:ySatcPKUqgp1QHyjB8lQSOCn8KXlf2hbwdrQNQxDWeioeLb7xN1sMrDcVcDGNRcs2wn12Ko+2JwUZ3qWONaCwoBnKUD2yM30BXtKCu6ggmgARWfd3lsQ/nUa5t1My/BOw+9mH0sBqt2ej86XS99ScFZiFZFPVwKMKOfJ4kfBOOc=,iv:2QyFapBwidI36t2YeCR0e0Fx0KwVw3t/7j1GKUpl9yk=,tag:A2uDVvAfSN6mK8b51I8PMw==,type:str]
    version: 3.13.3
