apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nextcloud
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:Ig9ofJUOVCn6,iv:1pUzi2oz+yBr3ofViG3QYcyiSQmoZptemEs289oApGY=,tag:qUXT4NxBGAqunlTuNHco6w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:hb9RO91MBfWx,iv:Qw1AWwEN3SsbGYgZXxXHWQg2N8CGdxoTeh8V7iR9MJM=,tag:rfA0enyO9Goscc+WZRy/OQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:PXppfxEwNl8suVSAi8tEmjj0wWQVL+nF,iv:cfgkFCNkGZa46J/sFhkZBzxgPk+QutnWeP3IQC7bjOs=,tag:v5WuzhL0tQDWEgl5bG/RpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGekEwRnFBbWJPd1RPcTVH
            QVdvdkQ1WklPSkFYTllaSXlBaFJwS2kzbVNZCm1kK1BlWmcvbENjZjZ5dVJYa3NW
            VkpPQmhVdDdsYmw2QU1ybk9Sd0EwOFUKLS0tIFBNbDNkSTdRUGlzSkROZkcyYmF1
            WU5KeTVMTlJhcVlKZGIycGVGajlnS0UKTM/DkKrZaAQ0Q+MDxdXXOKIA08ZEEU7z
            SMiLoaTZ2dPMN5VW/rvbaWjssfwdW2mM3ZGUzEMihMdT5dssZd2bPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wu2jzk553srljakk8n6uwsfaqh7qdl40htxavzxtjn2yllzq4c0qqg2dtk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:37:23Z"
    mac: ENC[AES256_GCM,data:YiPK/JzPLkvSdltpW5U/uAGUyFgB8KdLhyF74AugeVcZSXhvyZdah14eFq1oAn1q+nHhky30vRkgC1qa5pRIMX9bPtpFnklnl7PASVfNYgqPZJKUCbAu3tXDZ/dGf8VzWu3yIKDGubTfwEMVZAMKUZbloSTyaqGDthD8i+rar0s=,iv:NNk1IjNq8WG2Xx6RthlnvsDyLqGBYpi260+bqu+c5ss=,tag:aF02ud5hE1M4kG07iYnJMA==,type:str]
    version: 3.13.3
