apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ZahaanMahajan/homelab.git
    targetRevision: main
    path: kubernetes/apps/portfolio
    directory:
      exclude: "**/*.sops.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
