apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
