apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-routing
  namespace: default
spec:
  ingressClassName: traefik

  tls:
    - hosts:
        - app1.zahaan.online
      secretName: app1-zahaan-online-tls

  rules:
    - host: app1.zahaan.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app1-service
                port:
                  number: 80

    - host: app2.zahaan.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app2-service
                port:
                  number: 80
