apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <pvc-name>
  namespace: <namespace>
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <storage-class>
  resources:
    requests:
      storage: 5Gi
