apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:ZCirdyo=,iv:T9Fq0IzaiM7vwxXzm+MVdGo7SrdR2/DnMehvOjcYplQ=,tag:2I5RI3GMW6H9G3tx6cGsGA==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:I3kQfG9U9Wy+olCrOBWx1Q==,iv:afbqKf8SUMGEQTb8zeV0RiGV1fENQAU2thVjx3kFaNc=,tag:QXAv5mguwRI37+HuN1lzSg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:qnM/Xgxr5gc9,iv:jDByH5PKxs4DD/bdthe6zHlWqdGlEzJ/hOfzz3s9xdw=,tag:Xb1VwdI7ZwonmSAxD6MvNw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:GNZDj0PInxtT,iv:b9D4kGptOopARrgPrgRJ6PPRIu5bOgqV86zRs0BPEQM=,tag:FjNMx4TU2xV95NZ3wZpakQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QuRhNSbY4ervisrNLS3yILqAt7ERMOCR,iv:16t8Sd3GHjToagwIJ8RYMwH097yePALnB8CjbOhdtHQ=,tag:fecvfN5hXmEmtdfWkw0LMw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3fb7DS9hKo7UhQQUlDD972Bn8nV3,iv:j0Pnnhf2AX2EhAhFnyBWMqI7jPutPyGSbWxef54X/no=,tag:GPAStyXDAsRNXeO8XPIrgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXclVVVS9TeWd2cEU4cDBp
            TTZLem5SUzVCSFVhazBkZDFHZUluZG9JSFVjCmFScVI0U3hlVzZ2b0hFVDBLZUdv
            NTN0Vm90ODJOTkFzSHRBWVFicm5hRk0KLS0tIFlUWFdVU2VQNUwwL2Z4YUtkN0lD
            TmU4d1VXNlpWVVJIKy85QWZnaFJ2RUkKoyvd2ghgisIxVrZRQzIn3J4wL32dWYGE
            vkqOmUd0vfbHs6GvYLVnHUsQekIwKnOOb1PSNGpe6sroo6EVR7wrQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wu2jzk553srljakk8n6uwsfaqh7qdl40htxavzxtjn2yllzq4c0qqg2dtk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T09:10:13Z"
    mac: ENC[AES256_GCM,data:WWYPtOWw1DTN3m1u6Qj0cOy6osfmxjgDlxNJ0UthUavQ/4TJde4k4f9bVnJCnhTJl4q1OyWqML6pJGY4NVuhquVOvTOTWxJUlQ6uVzcScZne6idA/IulEvmz0bRL/fhUnUuo4Z7H+3TrTFVHuq1nu6hlimbPiCKOSQ+pGb1OY+8=,iv:vqsCMw7si2duZ00WHqGjFWtT3ScxigXVXSIQGXLfmPU=,tag:iZmDBgbipffQaqHfl+Whyw==,type:str]
    version: 3.13.3
