apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
