apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
type: Opaque
stringData:
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:l6ecJb8=,iv:KYbcSHYWfovLRT3LOxW+cBgTEynStGLc0YJruIG1io8=,tag:+3JUxH/6RO2JvIuXm5+Rtw==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:nTmNqX0+zvDdyvlvlbfz8g==,iv:FvMg8DSRBSHmgIrv5e11vCPcWrM/f8xtwFSUrueKuW0=,tag:68Fyoc8cm1Q1v/Z8j0koJw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ED/SAYqf2lPL,iv:ekPAZn2/NXvhZOrdcOYPl4Q2wQFjB7CsUjDFekSwFwE=,tag:AvIQYyhKLCZ92WITZFQ0NA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:SU7Rncj+HdVh,iv:KdAN7TUjVccCwewZggYw0+PqY86DCauSaoMWe85q0eU=,tag:lGlNF77tvMwxJAi1kyp4UA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3DToPeaBrU33XcUGUIAkQDLhayAKp5xF,iv:tnnciLioC+2OYqFfrJPBXUhe68wVJ6zZkZm/eZadwaQ=,tag:sMRY3/LobzVN5erbnIoY6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NTBNRzdXS011WkMvbFFh
            OW9SUUhCWEhLQTVpMHFGNE5aQ0xGQ1d6dVI0CjdxdG9SdFlqU1FSbHF3MWR2Qmlw
            aXFtUFFkNnJUaFl3UVlXRlJvb0R2YlkKLS0tIE5tV1NSNjE5dlhPTjM0MitWQ1pL
            Nm9CMFRVbzBYQkNMNnZBL1dlOWZ4K0UKdziCPIQbd0WU0EsZ8Cbm9IWqcfWgTOT9
            Hr5dzVJoJ9SdZAHhnUEZSpczZllv95BF3UD0z53qI5DT052s5hMdfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wu2jzk553srljakk8n6uwsfaqh7qdl40htxavzxtjn2yllzq4c0qqg2dtk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:45:33Z"
    mac: ENC[AES256_GCM,data:LrrXFHIKoQtaffB5ufdmhRZp+J+GLVqUfVUpIPO3Vv9XEqZj4vlitCOI9dAQ257LYW2eFghZ+Wu26YokcT6z4XjRozubHiRapoLVF1OZKDyHGcVC41jO5P7yqa74gNmcsSTwKP9DYiJyAUox2Rth5FwU5JqNsX86636XB0Xgztg=,iv:N+OnTSvQ+DP6JWzFlshMr7SIov0eOb2f+kYZliOPROU=,tag:s6D50MvOpsDdz4/wHLLIBA==,type:str]
    version: 3.13.3
