apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkding.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "linkding.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "linkding.selectorLabels" . | nindent 8 }}

    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}

      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}

      containers:
        - name: linkding
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 9090
              protocol: TCP

          env:
            - name: LD_CSRF_TRUSTED_ORIGINS
              value: {{ .Values.application.csrfTrustedOrigins | quote }}

            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username

            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password

          volumeMounts:
            - name: linkding-data
              mountPath: {{ .Values.persistence.mountPath }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: {{ include "linkding.fullname" . }}-data
