apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:XV3EjdA=,iv:zB6zCnbcjB7FHuNgI2iAfOL+pq3s1QuDxYgH5zWgjHw=,tag:/DawhcW8D0Ql92Ngx0A0TA==,type:str]
    password: ENC[AES256_GCM,data:8tqp4Ph0HKJz/Q/h7Zog,iv:+RVxqI7q5L7KaYwn1icpNKecTprGClyHYyNRo0Wb5R8=,tag:MXUcztcmp9R+o241HtT9FA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNG4zUHhiMUlBd0xRU0Ru
            RDY5TjA3YkpOUm9xV3hzUUZuTnYva2dPbkQ0ClJxT2ZqeE10T2VuYnVuUGJEVjNH
            SHEzb2cxMGtvejA4UUpFeVMxUlYxWVkKLS0tIEl6Z1loaklCS28wUGV1VHN3aVVE
            WTJVVkpsTlM5cVBGWjN5MmdrdVIyRG8Ko51rJcdodvH8ndLHJLvrEYoeEMKEDi9u
            qbluWwsIs7X3+AJWq9712Xfgr8NKJ1kYUI/Cn2zAsLY0rA/s/95caQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wu2jzk553srljakk8n6uwsfaqh7qdl40htxavzxtjn2yllzq4c0qqg2dtk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T11:46:08Z"
    mac: ENC[AES256_GCM,data:N1a3wIzppUV3lA65R5nB45NUdRQr3O354pbdS2STtVnQTtfQLM7qc2InAmqB4iAYYfEF5nlwPPBvfFB1NjZf9r+LionI1g+JCv/cdNNEbT/w+9huobIMBUtSNDtzr2VxTLUNQeH+QM7XueOPOM4HuM/QbMaiVJF4afBUJtyjfCk=,iv:mSZGhBi7RfuRKN1aOOOA6Zo3k1uIvMPbBtNCwzJtPg8=,tag:ezsqOraDRIG3JcMO4vp2gg==,type:str]
    version: 3.13.3
