apiVersion: v1
kind: Secret
metadata:
    name: ghcr-creds
    namespace: portfolio
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:BuU3RyawbOJBcdbhKxuN4c2kDeWNy6Nlktgk302+LjStb3NBsy2rIZV/1bo096Gpe9UJhOIn+xxhsZPsSYM3h5wg+70yw+o6eJcDUjUZaUni9cOh5A7b9xb0P/8V+KbLdWH7FQA2+5ejAomWmGyyri/YVFNgcM7HYaQO6bhayDO65qyCUtqH/0Jz/3vdtgStaWPO/nbHbjP94ZTY/4nc5ScMCAZnZ1Cl/JQmJZXNER893SX+VaCvbR2RhqvRyXEo5FD/UQ8cTIJxIqnB9ncF+Zam5R11ZYeKFvE52X1XzUKLDvRU6D2IF32lrGy1ALqJyFY4NCT6aE4=,iv:PuIMUQry66OBLkSNx7n2TyVpeNNVxfG0uWLVt9zDpK4=,tag:FQBb/54MHa3+gzYCJS8QOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS3pua3V4R2dxRGcyTlFi
            RWExbVhzZUhhOHUvaDFMZFRJamxHcktXakVnCmxFSDFOWmhsZ2g3aXpoZGg4Szln
            VFZHU2kwWFZBU21ZZ2ZQQXEvK1poUncKLS0tIHc4a0JFbGFub0cvM043c1FrZFo4
            L2FQT2h3ckUxRjM0ZUtpRnVYOU0xd1EKGbXwKs9GlQ8joCr9a2lvAISpYeNAwC+c
            EoIdplD4/w4eq4SXqoQ0tS0S8p3iNDrb4DifXPjCh+ACXzOyQhZRjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wu2jzk553srljakk8n6uwsfaqh7qdl40htxavzxtjn2yllzq4c0qqg2dtk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T12:00:00Z"
    mac: ENC[AES256_GCM,data:O6p24elBN/hlfmrLiWmfFA0fOf7wFWRf26Sn74d6VWmQrny7JVXGyXANm7TkqXytgaQIfwBpb1KsjqKoW0uKUX9h2am3QOibfEi2tmO7+EjPkI4/J3m/uXUzfP5jBjva5h3MceND2mlCnNPRusevgSvg5Pcphjc3uCf+QhthRS8=,iv:ynX6XdMr36R6Rk/j4jW4aB1aGKHD/xSoktePKQgPhwU=,tag:aYMfsPrOjFasUsXqvGDD9Q==,type:str]
    version: 3.13.3
