{{- if .Values.envoyProxy.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.envoyProxy.name }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                metallb.io/loadBalancerIPs: "{{ .Values.envoyProxy.loadBalancerIP }}"
{{- end }}
