apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      nodeSelector:
        {{- toYaml .Values.redis.nodeSelector | nindent 8 }}

      tolerations:
        {{- toYaml .Values.redis.tolerations | nindent 8 }}

      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          command:
            - redis-server

          args:
            - --requirepass
            - $(REDIS_PASSWORD)

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: REDIS_PASSWORD

          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}

          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
